# Generated by Django 3.2.10 on 2023-06-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_publicroomchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClusterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterName', models.TextField(default='Cluster <function GroupClusterList.<lambda> at 0x000001F0771497E0>', unique=True)),
                ('clusterChatCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='chartroomlist',
            name='clusterGroupId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatApp.groupclusterlist'),
        ),
    ]
