# Generated by Django 3.2.10 on 2023-06-13 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_auto_20230613_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartroomlist',
            name='clusterGroupId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatApp.groupclusterlist'),
        ),
        migrations.AlterField(
            model_name='groupclusterlist',
            name='clusterName',
            field=models.TextField(default='Cluster <function GroupClusterList.<lambda> at 0x00000169F3F79870>', unique=True),
        ),
    ]
