# Generated by Django 3.2.10 on 2023-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_auto_20230613_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartroomlist',
            name='clusterGroupId',
        ),
        migrations.AlterField(
            model_name='groupclusterlist',
            name='clusterName',
            field=models.TextField(default='Cluster <function GroupClusterList.<lambda> at 0x000001B5FDD39870>', unique=True),
        ),
    ]
